version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python --version
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install pytest
            pip install flask
            pip install pylint

      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pytest

      - run:
          name: Perform static analysis
          command: |
            source venv/bin/activate
            pylint -d C0116 app.py

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

