version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Update package lists
          command: sudo apt-get update

      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y libxss1 libappindicator1 libindicator7
            sudo apt-get install -y fonts-liberation
            python --version
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install pytest-cov
            pip install flask
            pip install pylint
            pip install coverage
            pip install robotframework
            pip install robotframework-seleniumlibrary
            pip install selenium

      - run:
          name: Install Google Chrome
          command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      - run:
          name: Start Chrome driver
          command: google-chrome-stable --disable-dev-shm-usage --remote-debugging-port=9222 http://localhost &

      - run:
          name: Run python program
          command: |
            source venv/bin/activate
            python3 app.py &

      - run:
          name: Run acceptance tests
          command: |
            cd tests
            robot --outputdir results/ test.robot

      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pytest --cov
            coverage report -m

      - run:
          name: Perform static analysis
          command: |
            source venv/bin/activate
            pylint -d C0116,C0114 app.py

      - run:
          name: Kill python program
          command: |
            source venv/bin/activate
            pkill -f app.py

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

