version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            python -m venv pytest
            source venv/bin/activate
            pip freeze requirements.txt

      - run:
          name: Run tests
          command: pytest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
