version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python --version
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install pytest-cov
            pip install flask
            pip install pylint
            pip install coverage
            pip install robotframework
            pip install robotframework-seleniumlibrary
            pip install selenium

      - run:
          name: Install Firefox
          command: |
            source venv/bin/activate
            sudo snap install firefox --classic

      - run:
          name: Run python program
          command: |
            source venv/bin/activate
            python3 app.py &

      - run:
          name: Run acceptance tests
          command: |
            source venv/bin/activate
            Xvfb :99 -screen 0 1024x768x24 &
            export DISPLAY=:99
            cd tests
            robot --outputdir results/ test.robot

      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pytest --cov
            coverage report -m

      - run:
          name: Perform static analysis
          command: |
            source venv/bin/activate
            pylint -d C0116,C0114 app.py

      - run:
          name: Kill python program
          command: |
            source venv/bin/activate
            pkill -f app.py

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

