version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Install Chrome and dependencies
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable xvfb
      - run:
          name: Install Robot Framework and Flask
          command: |
            pip install robotframework robotframework-seleniumlibrary Flask
      - run:
          name: Run Robot Framework tests
          command: |
            xvfb-run -a robot tests/
    working_directory: ~/project
