version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9.5-buster
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run:
          name: Install Chrome
          command: |
            sudo add-apt-repository universe
            sudo apt-get update
            sudo apt-get install chromium-browser

      - run: wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz && tar -xvf geckodriver-v0.30.0-linux64.tar.gz && chmod +x geckodriver && sudo mv geckodriver /usr/local/bin/
      - run:
          name: Run python program
          command: python3 app.py &
      - run:
          name: Run robot tests
          command: |
            cd tests
            robot --outputdir results/ test.robot
      - run:
          name: Run tests
          command: |
            pytest --cov
            coverage report -m
      - run:
          name: Perform static analysis
          command: |
            source venv/bin/activate
            pylint -d C0116,C0114 app.py
      - run:
          name: Kill python program
          command: |
            pkill -f app.py
