version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8-browsers

    working_directory: ~/repo

    steps:
      - browser-tools/install-browser-tools
      - checkout

      - run:
          name: Install dependencies
          command: |
            python --version
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install pytest-cov
            pip install flask
            pip install pylint
            pip install coverage
            pip install robotframework
            pip install robotframework-seleniumlibrary
      - run:
          name: Run python program
          command: |
            source venv/bin/activate
            python3 app.py &
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pytest --cov
            coverage report -m
            cd tests
            robot test.robot
      - run:
          name: Perform static analysis
          command: |
            source venv/bin/activate
            pylint -d C0116,C0114 app.py
      - run:
          name: Kill python program
          command: |
            source venv/bin/activate
            pkill -f app.py
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
